/** Industry-standard revenue & accounting report packs for the agency console. */
export const REPORT_CATALOG = [
  {
    id: 'collection',
    code: 'RCP',
    title: 'Collection Performance',
    subtitle: 'Confirmed collections, conversion, and period-on-period growth',
    category: 'Management',
    audience: 'Executive · Treasury · Audit',
    standards: ['IPSAS cash basis', 'Management reporting'],
  },
  {
    id: 'aged-receivables',
    code: 'AR-AGE',
    title: 'Aged Receivables',
    subtitle: 'Outstanding invoices aged by due date (current, 31–60, 61–90, 90+ days)',
    category: 'Receivables',
    audience: 'Finance · Credit control · Audit',
    standards: ['AR aging schedule', 'IFRS 9 credit exposure view'],
  },
  {
    id: 'cash-receipts',
    code: 'CRJ',
    title: 'Cash Receipts Journal',
    subtitle: 'Day-book of confirmed receipts with payer, channel, and invoice reference',
    category: 'Cash book',
    audience: 'Cashier · Treasury · Internal audit',
    standards: ['Cash receipts journal', 'Revenue cash book'],
  },
  {
    id: 'revenue-gl',
    code: 'REV-GL',
    title: 'Revenue by Type & GL',
    subtitle: 'Recognised revenue lines mapped to fee types and general-ledger codes',
    category: 'Revenue recognition',
    audience: 'Finance · Chart of accounts · Audit',
    standards: ['Revenue by account', 'Fee schedule analysis'],
  },
  {
    id: 'treasury-settlement',
    code: 'TSA',
    title: 'Treasury Settlement & Remittance',
    subtitle: 'Settlement batches and payment remittances to treasury / TSA accounts',
    category: 'Treasury',
    audience: 'Treasury · Accountant-General liaison',
    standards: ['TSA remittance register', 'Settlement batch control'],
  },
  {
    id: 'refunds',
    code: 'REF',
    title: 'Refunds & Adjustments',
    subtitle: 'Refunds processed against collections with reason and status control',
    category: 'Adjustments',
    audience: 'Treasury · Compliance · Audit',
    standards: ['Refund register', 'Contra-revenue control'],
  },
  {
    id: 'payment-channels',
    code: 'CHN',
    title: 'Payment Channel Performance',
    subtitle: 'Collections by gateway provider and payment method',
    category: 'Operations',
    audience: 'Payments ops · Treasury · IT',
    standards: ['Channel mix', 'Gateway reconciliation support'],
  },
  {
    id: 'officer-productivity',
    code: 'OFF',
    title: 'Officer Assessment Productivity',
    subtitle: 'Assessments raised by officer with value and workflow status mix',
    category: 'Operations',
    audience: 'Branch managers · Compliance',
    standards: ['Officer productivity', 'Assessment control'],
  },
  {
    id: 'branch-comparative',
    code: 'BRN',
    title: 'Branch / Command Comparative',
    subtitle: 'Collections, outstanding, and assessment volume by branch or command',
    category: 'Comparative',
    audience: 'Regional management · Executive',
    standards: ['Branch scorecard', 'Comparative performance'],
  },
] as const;

export type ReportPackId = (typeof REPORT_CATALOG)[number]['id'];
